#!/bin/sh

# INFO: requires httpie (brew install httpie)

# # GET trigger DATA action
# http GET http://localhost:5000/api/data/zfa6521e-a123-4a76-a04e-c367b6da169a




# GET trigger DATA action

# add job again (in case the middleware server has been restarted)
http POST http://localhost:5000/api/jobs \
  < ../resources/mock_blue_simulation/job.json

http GET http://localhost:5000/api/data/f17f97ea-ea74-468e-b637-b78f53f03b2d
